CREATE TABLE IF NOT EXISTS `order_returns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `order_id` int(11) NOT NULL,
  `order_item_id` int(11) DEFAULT NULL,
  `reason` enum('too_small','too_large','damaged','not_as_described','wrong_item','changed_mind','other') NOT NULL,
  `note` varchar(500) DEFAULT NULL,
  `status` enum('requested','approved','rejected','received','refunded','cancelled') NOT NULL DEFAULT 'requested',
  `refund_cents` int(10) unsigned DEFAULT NULL,
  `requested_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `processed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_order_returns_user` (`user_id`),
  KEY `idx_order_returns_order` (`order_id`),
  KEY `idx_order_returns_status` (`status`),
  KEY `fk_order_returns_item` (`order_item_id`),
  CONSTRAINT `fk_order_returns_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_order_returns_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_order_returns_item` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
